name: feature-pipeline-10min

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

  workflow_dispatch:

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    container:
      image: python:3.11.9-slim  # Use a compatible Docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          pip install nbclient

      - name: Run Jupyter Notebook
        run: |
          poetry run python -m nbclient --execute --to notebook --inplace /Users/borja/Documents/Somniumrema/projects/ml/taxi_demand_predictor/notebooks/industrialization/12_feature_pipeline.ipynb

      - name: Make features
        env: 
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: make features