name: feature-pipeline-15-min

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes

  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 1.8.3
  POETRY_URL: https://install.python-poetry.org

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: curl -sSL ${{ env.POETRY_URL }} | python3 - --version ${{ env.POETRY_VERSION }}
      
      - name: Copy files to correct location
        run: |
          mkdir -p /home/runner/work/prediction_model/prediction_model/src/taxi_demand_predictor
          cp -r /home/runner/work/prediction_model/src/* /home/runner/work/prediction_model/prediction_model/src/taxi_demand_predictor/
          mkdir -p /home/runner/work/prediction_model/prediction_model/notebooks/industrialization
          cp -r /home/runner/work/prediction_model/notebooks/industrialization/* /home/runner/work/prediction_model/prediction_model/notebooks/industrialization/

      - name: Install dependencies
        run: poetry install

      - name: Run Jupyter Notebook
        run: |
          poetry run python -m nbclient --execute --to notebook --inplace /home/runner/work/prediction_model/prediction_model/notebooks/industrialization/12_feature_pipeline.ipynb

      - name: Make features
        env: 
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: make features

